name: CI
on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:

  slurm:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Apptainer
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            sudo apt-get update
            sudo apt-get install -y rpm2cpio
            sudo apt-get install -y golang-go
            mkdir -p ~/apptainer
            # echo 'export PATH="$HOME/apptainer/bin:$PATH"' >> ~/.bashrc
            echo "$HOME/apptainer/bin" >> $GITHUB_PATH
            curl -s https://raw.githubusercontent.com/apptainer/apptainer/03bb84afc90c9699816db2e2730b56f2d3501eff/tools/install-unprivileged.sh | bash -s - ~/apptainer
      - name: Test Apptainer
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            apptainer --version
            sudo "$(which apptainer)" exec docker://busybox:latest echo "Hello from Singularity and Docker!"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git lshw python3.10-venv
      - name: Test scripts
        run: |
          for script in $(find slurm -name "*.sh"); do
            echo "${script}"
            ./${script}
          done
